### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by ka-coded** [bo-mathadventure/admin#1]
Hey, this is great work! I tried to run it, but got some errors in the frontend Dockerfile. Could you provide a working tutorial?

Failed to compile.

./src/components/DateSelector/DateSelectorPicker.tsx:46:4
Type error: 'DayPicker' cannot be used as a JSX component.
  Its instance type 'DayPicker' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/app/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
        Type 'PromiseLikeOfReactNode' is not assignable to type 'ReactNode'.

  44 |
  45 |   const dayPicker: React.ReactNode = (
> 46 |   <DayPicker
     |    ^
  47 |     locale={i18n.language}
  48 |     initialMonth={date.toDate()}
  49 |     selected={date.toDate()}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1

**Comment by Gurkengewuerz** [comment]
Hello @ka-coded thank you for your interest.
this project is still in development. we finished the backend but the frontend must still be done. since this project is part of a science project at the Hochschule Bochum – Bochum University of Applied Sciences we are gonna finish this project but we don't have any timeline!

because of this i will close this "issue".
